name: Run Stock Alert

on:
  schedule:
    - cron: "*/1 7-23 * * *"   # Alle 5 Minuten von 07:30 bis 22:30 UTC
  #workflow_dispatch:           # Manuell starten möglich

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'   # oder '7.0.x', je nachdem was du nutzt

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Run app
        run: dotnet run --project ConsoleApp1.csproj
